### ISSUE TITLE
Missing Realm constructor on app start

### ISSUE THREAD

**Issue by ghost** [LinkPact/React-API-experiment#2]
I'm getting this error when trying to run the app on my phone through expo:

> Missing Realm constructor. Did you run `react-native link realm`? Please see [https://realm.io/docs/react-native/latest/#missing-realm-constructor](https://realm.io/docs/react-native/latest/#missing-realm-constructor) for troubleshooting

The link says to add `java import io.realm.react.RealmReactPackage;` to `MainApplication.java` and `new RealmReactPackage()` to the `getPackages`-method in the same file but 1) there is no `MainApplication.java` file 2) there is no file with a getPackages method and 3) we don't even use java 

### What I've tried
I tried linking realm by running: `npm install -g react-native-cli` and 'react-native link realm'

which gives

> Scanning 827 folders for symlinks in /home/danalm/git/ProjectMercury/React-API-experiment/node_modules (16ms)

I also tried downgrading npm to the recommended version of 4.6.1.

### Steps to reproduce
1. Clone repo
2. `npm install`
3. `npm start`
4. Open app by scanning QR-code

**Comment by martinbaste** [comment]
Apparently there is no support for Realm in Expo, is that correct? in this case we should close this
